{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ba3029c8-a398-4505-a3ce-088ace344299",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\catas\\anaconda3\\lib\\site-packages (1.37.1)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (24.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (5.29.5)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (16.1.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (13.7.1)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: watchdog<5,>=2.1.5 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from streamlit) (4.0.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: toolz in c:\\users\\catas\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\catas\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2025.8.3)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\catas\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4d5923f5-0000-42be-9938-c389ae5680c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-24 23:10:00.307 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\catas\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-09-24 23:10:00.307 Session state does not function when running a script without `streamlit run`\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import matplotlib.pyplot as plt\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# ML y preprocesamiento\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "# Configuración de la página\n",
    "st.set_page_config(\n",
    "    page_title=\"Predicción de Consumo Energético\",\n",
    "    page_icon=\"⚡\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"auto\",\n",
    ")\n",
    "\n",
    "# Sidebar de proyecto\n",
    "st.sidebar.title('Sobre Este Proyecto')\n",
    "st.sidebar.markdown(\"\"\"\n",
    "### Predicción de Consumo Energético\n",
    "\n",
    "Este modelo predice el consumo energético basado en:\n",
    "\n",
    "**Características Categóricas:**\n",
    "- Día de la semana\n",
    "- Feriado (Sí/No)\n",
    "- Uso de HVAC (Calefacción/AC)\n",
    "- Uso de Iluminación\n",
    "- Período del tiempo\n",
    "- Estación del año\n",
    "\n",
    "**Características Numéricas:**\n",
    "- Temperatura\n",
    "- Superficie en pies cuadrados\n",
    "- Ocupación (personas)\n",
    "- Distancia de temperatura de confort\n",
    "- Índice de calor\n",
    "\n",
    "### Modelo Utilizado\n",
    "- Algoritmo: Regresión Lineal\n",
    "- Preprocesamiento: StandardScaler + OneHotEncoder\n",
    "- Pipeline de scikit-learn\n",
    "\"\"\")\n",
    "\n",
    "# Intentar cargar el modelo entrenado\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    try:\n",
    "        model = joblib.load('LR_model.pkl')\n",
    "        return model, True\n",
    "    except:\n",
    "        st.warning(\"Modelo no encontrado. Usando modelo de demostración.\")\n",
    "        return None, False\n",
    "\n",
    "# Título principal\n",
    "st.title('⚡ Predicción de Consumo Energético')\n",
    "st.markdown(\"---\")\n",
    "\n",
    "# Inputs en columnas\n",
    "col1, col2, col3 = st.columns(3)\n",
    "with col1:\n",
    "    st.markdown(\"### 📅 Información Temporal\")\n",
    "    day_of_week = st.selectbox(\n",
    "        'Día de la Semana',\n",
    "        ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],\n",
    "        index=0\n",
    "    )\n",
    "    holiday = st.selectbox('Feriado', ['No', 'Yes'], index=0)\n",
    "    time_period = st.selectbox(\n",
    "        'Período del Día',\n",
    "        ['Morning', 'Afternoon', 'Evening', 'Night'],\n",
    "        index=1\n",
    "    )\n",
    "    season = st.selectbox(\n",
    "        'Estación',\n",
    "        ['Winter', 'Spring', 'Summer', 'Fall'],\n",
    "        index=0\n",
    "    )\n",
    "with col2:\n",
    "    st.markdown(\"### 🌡️ Condiciones Ambientales\")\n",
    "    temperature = st.slider(\n",
    "        'Temperatura (°C)', \n",
    "        min_value=10.0, \n",
    "        max_value=35.0, \n",
    "        value=22.0, \n",
    "        step=0.5\n",
    "    )\n",
    "    comfort_temps = {'Winter': 20.0, 'Spring': 22.0, 'Summer': 24.0, 'Fall': 21.0}\n",
    "    temp_from_comfort = abs(temperature - comfort_temps[season])\n",
    "    st.info(f\"Distancia de temperatura de confort: {temp_from_comfort:.1f}°C\")\n",
    "    humidity_assumed = 50.0\n",
    "    heat_index = temperature + (0.5 * humidity_assumed)\n",
    "    st.info(f\"Índice de calor calculado: {heat_index:.1f}\")\n",
    "with col3:\n",
    "    st.markdown(\"### 🏢 Información del Edificio\")\n",
    "    square_footage = st.number_input(\n",
    "        'Superficie (pies cuadrados)', min_value=500, max_value=5000, value=1500\n",
    "    )\n",
    "    occupancy = st.number_input(\n",
    "        'Ocupación (personas)', min_value=1, max_value=20, value=5\n",
    "    )\n",
    "    hvac_usage = st.selectbox(\n",
    "        'Uso de HVAC', ['Off', 'On'], index=1\n",
    "    )\n",
    "    lighting_usage = st.selectbox(\n",
    "        'Uso de Iluminación', ['Off', 'On'], index=1\n",
    "    )\n",
    "\n",
    "# Botón de predicción centrado\n",
    "st.markdown(\"---\")\n",
    "col_center = st.columns([1, 2, 1])\n",
    "with col_center[1]:\n",
    "    predict_button = st.button('🔮 Predecir Consumo Energético', use_container_width=True)\n",
    "\n",
    "if predict_button:\n",
    "    with st.spinner('Calculando predicción...'):\n",
    "        input_data = pd.DataFrame({\n",
    "            'DayOfWeek': [day_of_week],\n",
    "            'Holiday': [holiday],\n",
    "            'Temperature': [temperature],\n",
    "            'SquareFootage': [square_footage],\n",
    "            'Occupancy': [occupancy],\n",
    "            'HVACUsage': [hvac_usage],\n",
    "            'LightingUsage': [lighting_usage],\n",
    "            'TimePeriod': [time_period],\n",
    "            'Season': [season],\n",
    "            'TempFromComfort_Seasonal': [temp_from_comfort],\n",
    "            'HeatIndex': [heat_index]\n",
    "        })\n",
    "        categorical_features = [\n",
    "            \"DayOfWeek\", \"Holiday\", \"HVACUsage\", \"LightingUsage\", \"TimePeriod\", \"Season\"\n",
    "        ]\n",
    "        numerical_features = [\n",
    "            \"Temperature\", \"SquareFootage\", \"Occupancy\", \"TempFromComfort_Seasonal\", \"HeatIndex\"\n",
    "        ]\n",
    "        model, model_exists = load_model()\n",
    "        if model_exists:\n",
    "            try:\n",
    "                prediction = model.predict(input_data[numerical_features + categorical_features])[0]\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error usando el modelo: {e}\")\n",
    "                prediction = None\n",
    "        else:\n",
    "            base_consumption = square_footage * 0.05\n",
    "            temp_factor = temp_from_comfort * 2\n",
    "            occupancy_factor = occupancy * 3\n",
    "            hvac_factor = 15 if hvac_usage == 'On' else 0\n",
    "            lighting_factor = 8 if lighting_usage == 'On' else 0\n",
    "            season_factor = {'Winter': 10, 'Summer': 8, 'Spring': 3, 'Fall': 5}[season]\n",
    "            prediction = base_consumption + temp_factor + occupancy_factor + hvac_factor + lighting_factor + season_factor\n",
    "            prediction += np.random.normal(0, 5)\n",
    "        if prediction is not None:\n",
    "            st.success(f\"Consumo Energético Predicho: {prediction:.2f} kWh\")\n",
    "            viz_col1, viz_col2 = st.columns(2)\n",
    "            with viz_col1:\n",
    "                st.markdown(\"### 📊 Resultado de Predicción\")\n",
    "                fig_gauge = go.Figure(go.Indicator(\n",
    "                    mode = \"gauge+number\",\n",
    "                    value = prediction,\n",
    "                    domain = {'x': [0, 1], 'y': [0, 1]},\n",
    "                    title = {'text': \"Consumo Energético (kWh)\"},\n",
    "                    gauge = {\n",
    "                        'axis': {'range': [None, max(100, prediction*1.5)]},\n",
    "                        'bar': {'color': \"#1f77b4\"},\n",
    "                        'steps': [\n",
    "                            {'range': [0, 50], 'color': \"lightgreen\"},\n",
    "                            {'range': [50, 80], 'color': \"yellow\"},\n",
    "                            {'range': [80, 120], 'color': \"orange\"}\n",
    "                        ],\n",
    "                        'threshold': {\n",
    "                            'line': {'color': \"red\", 'width': 4},\n",
    "                            'thickness': 0.75,\n",
    "                            'value': prediction\n",
    "                        }\n",
    "                    }\n",
    "                ))\n",
    "                fig_gauge.update_layout(height=300)\n",
    "                st.plotly_chart(fig_gauge, use_container_width=True)\n",
    "            with viz_col2:\n",
    "                st.markdown(\"### 🔍 Análisis de Factores\")\n",
    "                factors = {\n",
    "                    'Superficie': square_footage / 50,\n",
    "                    'Ocupación': occupancy * 8,\n",
    "                    'Temperatura': temp_from_comfort * 3,\n",
    "                    'HVAC': 15 if hvac_usage == 'On' else 5,\n",
    "                    'Iluminación': 10 if lighting_usage == 'On' else 2,\n",
    "                    'Estación': {'Winter': 12, 'Summer': 10, 'Spring': 6, 'Fall': 8}[season]\n",
    "                }\n",
    "                df_factors = pd.DataFrame(\n",
    "                    list(factors.items()), columns=['Factor', 'Contribución']\n",
    "                )\n",
    "                fig_bar = px.bar(\n",
    "                    df_factors, \n",
    "                    x='Factor', \n",
    "                    y='Contribución',\n",
    "                    color='Contribución',\n",
    "                    color_continuous_scale='RdYlGn_r',\n",
    "                    title=\"Contribución Estimada por Factor\"\n",
    "                )\n",
    "                fig_bar.update_layout(height=300)\n",
    "                st.plotly_chart(fig_bar, use_container_width=True)\n",
    "            st.markdown(\"### 💡 Análisis Detallado\")\n",
    "            analysis_col1, analysis_col2 = st.columns(2)\n",
    "            with analysis_col1:\n",
    "                st.markdown(\"**Factores que aumentan el consumo:**\")\n",
    "                factors_high = []\n",
    "                if temp_from_comfort > 3:\n",
    "                    factors_high.append(f\"• Temperatura alejada del confort ({temp_from_comfort:.1f}°C de diferencia)\")\n",
    "                if occupancy > 8:\n",
    "                    factors_high.append(f\"• Alta ocupación ({occupancy} personas)\")\n",
    "                if hvac_usage == 'On':\n",
    "                    factors_high.append(\"• HVAC encendido\")\n",
    "                if lighting_usage == 'On':\n",
    "                    factors_high.append(\"• Iluminación encendida\")\n",
    "                if season in ['Winter', 'Summer']:\n",
    "                    factors_high.append(f\"• Estación extrema ({season})\")\n",
    "                if factors_high:\n",
    "                    for factor in factors_high:\n",
    "                        st.write(factor)\n",
    "                else:\n",
    "                    st.write(\"• Configuración optimizada para bajo consumo\")\n",
    "            with analysis_col2:\n",
    "                st.markdown(\"**Recomendaciones de ahorro:**\")\n",
    "                recommendations = []\n",
    "                if temp_from_comfort > 2:\n",
    "                    recommendations.append(\"• Ajustar temperatura más cerca del confort\")\n",
    "                if hvac_usage == 'On' and temp_from_comfort < 1:\n",
    "                    recommendations.append(\"• Considerar apagar HVAC si temperatura es cómoda\")\n",
    "                if lighting_usage == 'On' and time_period in ['Morning', 'Afternoon']:\n",
    "                    recommendations.append(\"• Usar luz natural durante el día\")\n",
    "                recommendations.extend([\n",
    "                    \"• Optimizar aislamiento del edificio\",\n",
    "                    \"• Usar dispositivos de alta eficiencia energética\",\n",
    "                    \"• Implementar sistemas de gestión inteligente\"\n",
    "                ])\n",
    "                for rec in recommendations[:5]:\n",
    "                    st.write(rec)\n",
    "\n",
    "# Información adicional\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"### 📋 Cómo Usar Esta Herramienta\")\n",
    "instructions_col1, instructions_col2 = st.columns(2)\n",
    "with instructions_col1:\n",
    "    st.markdown(\"\"\"\n",
    "    **Pasos:**\n",
    "    1. Selecciona la información temporal (día, feriado, período, estación)\n",
    "    2. Ajusta las condiciones ambientales (temperatura)\n",
    "    3. Ingresa los datos del edificio (superficie, ocupación, sistemas)\n",
    "    4. Haz clic en 'Predecir Consumo Energético'\n",
    "    5. Revisa el resultado y las recomendaciones\n",
    "    \"\"\")\n",
    "with instructions_col2:\n",
    "    st.markdown(\"\"\"\n",
    "    **Características del Modelo:**\n",
    "    - Basado en regresión lineal\n",
    "    - Considera 11 variables de entrada\n",
    "    - Incluye características de ingeniería (confort térmico, índice de calor)\n",
    "    - Pipeline con preprocesamiento automático\n",
    "    - Manejo de variables categóricas y numéricas\n",
    "    \"\"\")\n",
    "\n",
    "# Consejos en expander\n",
    "with st.expander(\"💡 Consejos de Eficiencia Energética\"):\n",
    "    st.markdown(\"\"\"\n",
    "    **Optimización de Temperatura:**\n",
    "    - Mantener temperatura entre 20-24°C según la estación\n",
    "    - Usar termostatos programables\n",
    "    - Mejorar aislamiento térmico\n",
    "    \n",
    "    **Gestión de Sistemas:**\n",
    "    - Apagar HVAC cuando no sea necesario\n",
    "    - Usar sensores de movimiento para iluminación\n",
    "    - Mantenimiento regular de equipos\n",
    "    \n",
    "    **Factores Estacionales:**\n",
    "    - Invierno: Optimizar calefacción, sellar corrientes de aire\n",
    "    - Verano: Usar ventilación natural, protección solar\n",
    "    - Primavera/Otoño: Aprovechar temperaturas moderadas\n",
    "    \"\"\")\n",
    "\n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"**Nota:** Esta aplicación utiliza un modelo de machine learning entrenado en datos históricos de consumo energético.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "54a745b4-c6d4-4791-a984-fba11309afdf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (pyspark_env)",
   "language": "python",
   "name": "pyspark_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
